import Sidebar from '@/components/Sidebar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex h-screen overflow-hidden'>
					<Sidebar />
					<main>
						<div className='mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10'>
							{children}
						</div>
					</main>
				</div>
			</body>
		</html>
	);
}
